# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'e4373e38-ef06-4bf5-a5d1-7985d14788e5'
  imageRepository: 'testbedphpsymfony'
  containerRegistry: 'locotechtestbed.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build the image
      inputs:
        command: build
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
              $(tag)
    - task: prisma-cloud-compute-scan@3
      displayName: Scan image for vurnelabilities
      inputs:
        scanType: 'images'
        twistlockService: 'twistme locotech'
        artifact: $(containerRegistry)/$(imageRepository):$(tag)
    - task: Docker@2
      displayName: Push the image to the registry
      inputs:
        command: push
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
              $(tag)           