<?php

namespace App\Api;

use ErrorException;
use OpenAPI\Server\Api\AppMetadataApiInterface;
use OpenAPI\Server\Model\AppMetadata;

class AppMetadataApi implements AppMetadataApiInterface // An interface is autogenerated
{
  protected string $projectDir;

  public function __construct(string $projectDir)
  {
    $this->projectDir = $projectDir;
  }

  public function appMetadata(&$responseCode, array &$responseHeaders) {

    // read version and name from app composer.json
    $data = \file_get_contents($this->projectDir.'/composer.json');

    $jsonObj = json_decode($data);

    $name = $jsonObj->name;
    $version = $jsonObj->version;

    return new AppMetadata([
      'name' => $name,
      'version' => $version,
      'hostname' => gethostname()
    ]);
  }

}
